---
deployment:
  tasks:
    - export DEPLOYPATH=/home/USERNAME/public_html/
    - /bin/cp -R _astro $DEPLOYPATH
    - /bin/cp -R about $DEPLOYPATH
    - /bin/cp -R apps $DEPLOYPATH
    - /bin/cp -R blog $DEPLOYPATH
    - /bin/cp -R events $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R pagefind $DEPLOYPATH
    - /bin/cp -R plugins $DEPLOYPATH
    - /bin/cp -R search $DEPLOYPATH
    - /bin/cp -R videos $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp favicon.svg $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
